#ifndef _MT6577_CLKMGR_H
#define _MT6577_CLKMGR_H

#include "mach/mt_clock_manager.h"

#endif /* !ifdef _MT6577_CLKMGR_H */
//
// CG_CLK ID
//
typedef enum cg_clk_id
{
// CG_MIXED
	MT_CG_SYS_26M,
	// MT_CG_UNIV_48M,
	MT_CG_USB_48M,

// CG_MPLL
	MT_CG_MPLL_D2,
	MT_CG_MPLL_D3,
	MT_CG_MPLL_D5,
	MT_CG_MPLL_D7,
	MT_CG_MPLL_D11,
	MT_CG_MPLL_D4,
	MT_CG_MPLL_D6,
	MT_CG_MPLL_D10,
	MT_CG_MPLL_D14,
	MT_CG_MPLL_D8,
	MT_CG_MPLL_D12,
	MT_CG_MPLL_D20,
	MT_CG_MPLL_D28,
	MT_CG_MPLL_D16,
	MT_CG_MPLL_D24,
	MT_CG_MPLL_D40,

//CG_INFRA_AO	
	MT_CG_PLL2_CK,
	
// CG_UPLL
	MT_CG_UPLL_D2,
	MT_CG_UPLL_D3,
	MT_CG_UPLL_D5,
	MT_CG_UPLL_D7,
	MT_CG_UPLL_D4,
	MT_CG_UPLL_D6,
	MT_CG_UPLL_D10,
	MT_CG_UPLL_D8,
	MT_CG_UPLL_D12,
	MT_CG_UPLL_D20,
	MT_CG_UPLL_D16,
	MT_CG_UPLL_D24,
	
//CG_CTRL0
	MT_CG_PWM_MM_SW_CG,
	MT_CG_CAM_MM_SW_CG,
	MT_CG_MFG_MM_SW_CG,
	MT_CG_SPM_52M_SW_CG,
	MT_CG_MIPI_26M_DBG_EN,
	MT_CG_SCAM_MM_SW_CG,
	MT_CG_SC_26M_CK_SEL_EN,
	MT_CG_SC_MEM_CK_OFF_EN,
	MT_CG_SC_AXI_CK_OFF_EN,
	MT_CG_ARM_EMICLK_WFI_GATING_DIS,
	MT_CG_ARMDCM_CLKOFF_EN,

//CG_CTRL1
	MT_CG_THEM_SW_CG,
	MT_CG_APDMA_SW_CG,
	MT_CG_I2C0_SW_CG,
	MT_CG_I2C1_SW_CG,
	MT_CG_AUXADC1_SW_CG,
	MT_CG_NFI_SW_CG,
	MT_CG_NFIECC_SW_CG,
	MT_CG_DEBUGSYS_SW_CG,
	MT_CG_PWM_SW_CG,
	MT_CG_UART0_SW_CG,
	MT_CG_UART1_SW_CG,
	MT_CG_BTIF_SW_CG,
	MT_CG_USB_SW_CG,
	MT_CG_FHCTL_SW_CG,
	MT_CG_AUXADC2_SW_CG,
	MT_CG_I2C2_SW_CG,
	MT_CG_MSDC0_SW_CG,
	MT_CG_MSDC1_SW_CG,
	MT_CG_NFI2X_SW_CG,
	MT_CG_PMIC_SW_CG_AP,
	MT_CG_SEJ_SW_CG,
	MT_CG_MEMSLP_DLYER_SW_CG,
	MT_CG_SPI_SW_CG,
	MT_CG_APXGPT_SW_CG,
	MT_CG_AUDIO_SW_CG,
	MT_CG_SPM_SW_CG,
	MT_CG_PMIC_SW_CG_MD,
	MT_CG_PMIC_SW_CG_CONN,
	MT_CG_PMIC_26M_SW_CG,
	MT_CG_AUX_SW_CG_ADC,
	MT_CG_AUX_SW_CG_TP,

//CG_CTRL2
	MT_CG_RBIST_SW_CG,
	MT_CG_NFI_BUS_SW_CG,
	MT_CG_GCE_SW_CG,
	MT_CG_TRNG_SW_CG,
	MT_CG_SEJ_13M_SW_CG,
	MT_CG_AES_SW_CG,
	MT_CG_PWM_BCLK_SW_CG,
	MT_CG_PWM1_FBCLK_SW_CG,
	MT_CG_PWM2_FBCLK_SW_CG,
	MT_CG_PWM3_FBCLK_SW_CG,
	MT_CG_PWM4_FBCLK_SW_CG,
	MT_CG_PWM5_FBCLK_SW_CG,

// CG_MMSYS0
	MT_CG_DISP0_SMI_COMMON,
	MT_CG_DISP0_SMI_LARB0,
	MT_CG_DISP0_FAKE_ENG,

// CG_MMSYS1
	MT_CG_DISP1_DISP_PWM_MM,
	MT_CG_DISP1_DISP_PWM_26M,
	MT_CG_DISP1_DSI_ENGINE,
	MT_CG_DISP1_DSI_DIGITAL,
	MT_CG_DISP1_DPI_PIXEL,
	MT_CG_DISP1_DPI_ENGINE,

// CG_IMGSYS
	MT_CG_LARB1_SMI_CKPDN,
	MT_CG_CAM_SMI_CKPDN,
	MT_CG_CAM_CAM_CKPDN,
	MT_CG_SEN_TG_CKPDN,
	MT_CG_SEN_CAM_CKPDN,
	MT_CG_VCODEC_CKPDN,

// CG_MFGSYS
	MT_CG_BG3D_SET,
	MT_CG_BG3D_CLR,

// CG_AUDIO

	MT_CG_AUD_PDN_AFE_EN,
	MT_CG_AUD_PDN_I2S_EN,
	MT_CG_AUD_PDN_ADC_EN,
	MT_CG_AUD_PDN_DAC_EN,
	NR_CLKS,

	CG_MIXED_FROM	= MT_CG_SYS_26M,
	CG_MIXED_TO	= MT_CG_USB_48M,
	CG_MPLL_FROM	= MT_CG_MPLL_D2,
	CG_MPLL_TO	= MT_CG_MPLL_D40,
	CG_UPLL_FROM	= MT_CG_UPLL_D2,
	CG_UPLL_TO	= MT_CG_UPLL_D24,
	CG_CTRL0_FROM	= MT_CG_PWM_MM_SW_CG,
	CG_CTRL0_TO	= MT_CG_ARMDCM_CLKOFF_EN,
	CG_CTRL1_FROM	= MT_CG_THEM_SW_CG,
	CG_CTRL1_TO	= MT_CG_AUX_SW_CG_TP,
	CG_CTRL2_FROM	= MT_CG_RBIST_SW_CG,
	CG_CTRL2_TO	= MT_CG_PWM5_FBCLK_SW_CG,
	CG_MMSYS0_FROM	= MT_CG_DISP0_SMI_COMMON,
	CG_MMSYS0_TO	= MT_CG_DISP0_FAKE_ENG,
	CG_MMSYS1_FROM	= MT_CG_DISP1_DISP_PWM_MM,
	CG_MMSYS1_TO	= MT_CG_DISP1_DPI_ENGINE,
	CG_IMGSYS_FROM	= MT_CG_LARB1_SMI_CKPDN,
	CG_IMGSYS_TO	= MT_CG_VCODEC_CKPDN,
	CG_MFGSYS_FROM	= MT_CG_BG3D_SET,
	CG_MFGSYS_TO	= MT_CG_BG3D_CLR,
	CG_AUDIO_FROM	= MT_CG_AUD_PDN_ADC_EN,
	CG_AUDIO_TO	= MT_CG_AUD_PDN_DAC_EN,
	MT_CG_INVALID,
//add for build error
	MT_CG_INFRA_UART0,
	MT_CG_INFRA_UART1,
	MT_CG_INFRA_UART2,
	MT_CG_INFRA_UART3,
	MT_CG_INFRA_GCE,
	MT_CG_INFRA_MSDC_0,
	MT_CG_INFRA_MSDC_1,
	MT_CG_DISP0_CAM_MDP,		//DCM
	MT_CG_DISP0_MDP_RDMA,		//DCM
	MT_CG_DISP0_MDP_RSZ0,		//DCM
	MT_CG_DISP0_MDP_RSZ1,		//DCM
	MT_CG_DISP0_MDP_TDSHP,		//DCM
	MT_CG_DISP0_MDP_WDMA,		//DCM
	MT_CG_DISP0_MDP_WROT,		//DCM
	MT_CG_DISP0_DISP_OVL0,		//DCM
	MT_CG_DISP0_DISP_RDMA0,		//DCM
	MT_CG_DISP0_DISP_WDMA0,		//DCM
	MT_CG_DISP0_DISP_COLOR,		//DCM
	MT_CG_DISP0_DISP_AAL,		//DCM
	MT_CG_DISP0_DISP_GAMMA,		//DCM
	MT_CG_DISP0_DISP_DITHER,	//DCM

} cg_clk_id;